"""add reservation_period in reservations for constraints

Revision ID: 33823f6aaaec
Revises: f8677e280735
Create Date: 2025-04-11 12:27:31.438162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33823f6aaaec"
down_revision: Union[str, None] = "f8677e280735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reservations", sa.Column("reservation_period", postgresql.TSRANGE(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservations", "reservation_period")
    # ### end Alembic commands ###
