"""change Date to DateTime in reservations table

Revision ID: f8677e280735
Revises: 68b0d58c6c52
Create Date: 2025-04-11 11:18:16.414409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8677e280735"
down_revision: Union[str, None] = "68b0d58c6c52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservations", "reservation_time", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reservations", "reservation_time", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=False
    )
    # ### end Alembic commands ###
