"""add no overlapping constraint

Revision ID: d52b05aa3aec
Revises: 33823f6aaaec
Create Date: 2025-04-11 15:11:34.778561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d52b05aa3aec"
down_revision: Union[str, None] = "33823f6aaaec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE reservations
        ADD CONSTRAINT no_overlapping_reservations
        EXCLUDE USING GIST (
            table_id WITH =,
            reservation_period WITH &&
        );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("no_overlapping_reservations", "reservations", type_="exclude")

    # ### end Alembic commands ###
